### ISSUE TITLE
TypeError: this.chart.render is not a function

### ISSUE THREAD

**Issue by yuhao-nyc** [apexcharts/react-apexcharts#42]
I saw a bunch of TypeScript issues around in this repo and `apexcharts` repo. But still couldn't solve my problem.
I'm integrating this React ApexChart lib into my TypeScript app. But after I import the component. I got this error. and the page is broken. Below is my code: 

```import * as React from 'react';
import Chart from 'react-apexcharts';

interface ApexChartProps {}

interface ApexChartState {
    options?: any;
    series?: any;
}

export class ApexChart extends React.Component<ApexChartProps, ApexChartState> {
    constructor(props: ApexChartProps) {
        super(props);
        this.state = {
            options: {
              chart: {
                id: 'basic-bar',
              },
              xaxis: {
                categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
              },
            },
            series: [
              {
                name: 'series-1',
                data: [30, 40, 45, 50, 49, 60, 70, 91],
              },
            ],
        };
    }

    public render(): React.ReactNode {
        return (
            <>
                <div className="app">
                    <div className="row">
                        <div className="mixed-chart">
                            Apex Chart
                            <Chart
                                options={this.state.options}
                                series={this.state.series}
                                type="bar"
                                width="500"
                                height="600"
                            />
                        </div>
                    </div>
                </div>
            </>
        );
    }
}
```

Can anyone share some thoughts?

![image](https://user-images.githubusercontent.com/4121735/53373573-cbf54c00-3923-11e9-84af-d52af2ce2964.png)

**Comment by junedchhipa** [comment]
@yuhao-nyc Thanks for reporting the error.

I have released a new version `react-apexcharts@1.3.0`
Can you please confirm if the latest version doesn't throw this error?

**Comment by yuhao-nyc** [comment]
@junedchhipa nope. still cant build the page. using the same code as above. now getting this error.

![image](https://user-images.githubusercontent.com/4121735/53444577-8f395b80-39dc-11e9-85f9-97dc4316b1cb.png)

**Comment by junedchhipa** [comment]
Is it possible for you to zip your project and send to `juned.chhipa (at) gmail (dot) com` ?
I can't reproduce it easily so would like to work directly in your environment.

Otherwise, please create a codesandbox

**Comment by yuhao-nyc** [comment]
@junedchhipa I'm sorry I don't have the bandwidth to zip the project or create the same environment in codesandbox rn. Also this is not a personal project. But I will try start up my own personal repo to replicate this issue.

Anyways the project is just a plain boilerplate. It's a TypeScript + React app. here's my deps. maybe you can tell if there's something missing or what have you. 

![image](https://user-images.githubusercontent.com/4121735/53523083-d93c4300-3aa9-11e9-9e23-34cb9c744dc1.png)

![image](https://user-images.githubusercontent.com/4121735/53523100-e822f580-3aa9-11e9-96d4-15ddf0c0cb7f.png)

**Comment by yuhao-nyc** [comment]
Also I know we are missing `@types/react-apexcharts`. But I high doubt that would be the issue here

**Comment by junedchhipa** [comment]
Thanks, I will try the boilerplate of react+typescript and see if the issue reproduces on my side.

**Comment by yuhao-nyc** [comment]
great! Please let me know if you made any progress. @junedchhipa

**Comment by PeterYangIO** [comment]
The more recent error you linked says `this.chart.render is not a function` and it only appears to be called within the library here:
https://github.com/apexcharts/react-apexcharts/blob/d98b037e27612d28d139a77f27566782094b2c7a/src/react-apexcharts.jsx#L31

My best guess is that something from the previous line prevents it from setting `this.chart` to a valid `ApexChart` object so `.render` does not exist on `this.chart`. It's possible this line returns `null` or `undefined`.
https://github.com/apexcharts/react-apexcharts/blob/d98b037e27612d28d139a77f27566782094b2c7a/src/react-apexcharts.jsx#L30 returns 

@junedchhipa Do you think that could be the case? I haven't tried this code myself to reproduce.

**Comment by jakebott** [comment]
I have also come across the same issue using Parcel to build (have not tested with other build systems).  A minimum working example can be found here: https://gist.github.com/jakebott/89a52ba9fedb90c4d206fce650de5a04

@PeterYangIO I placed a `console.log(this.chart)` call between lines 30 and 31:
![console log this chart](https://user-images.githubusercontent.com/44956758/55781634-ca55a100-5ae9-11e9-8c1d-737b78de0901.png)

**Comment by junedchhipa** [comment]
I just published `react-apexcharts@1.3.3`
Can you please test with the latest version and let me know if that fixed the issue?

**Comment by jakebott** [comment]
@junedchhipa That seems to have done the trick for me, it works perfectly now.  Much appreciated!

**Comment by junedchhipa** [comment]
Ok! Closing it for now.
Feel free to open this issue again if any user is experiencing the same bug.
